name: Build and Release Dylib

on: push

jobs:
  release:
    strategy:
      matrix:
        include:
          - image: macos-latest
            name: macos-amd64
            extension: dylib
            artifact: libed25519_bip32_macos-amd64.tar.gz
          - image: ubuntu-latest
            name: linux-amd64
            extension: so
            artifact: libed25519_bip32_linux-amd64.tar.gz
          - image: windows-latest
            name: windows-amd64
            extension: dll
            artifact: libed25519_bip32_windows-amd64.zip
          - image: [self-hosted, macos, arm64]
            name: macos-arm64
            extension: dylib
            artifact: libed25519_bip32_macos-arm64.tar.gz
          - image: [self-hosted, linux, arm64]
            name: linux-arm64
            extension: so
            artifact: libed25519_bip32_linux-arm64.tar.gz
    runs-on: ${{ matrix.image }}
    name: Release ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: make deps
      - name: Regenerate C Header and Check
        run: make diff
      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -v
      - name: Prepare files
        if: matrix.name != 'windows-amd64'
        run: |
          mkdir artifacts
          mv LICENSE ed25519_bip32.h target/release/libed25519_bip32.${{ matrix.extension }} artifacts
          #cd artifacts
          #tar -czf ${{ matrix.artifact }} *
      - name: Prepare files Windows
        if: matrix.name == 'windows-amd64'
        run: |
          mkdir artifacts
          Move-Item -Path LICENSE, ed25519_bip32.h -Destination artifacts
          # lib filename is different on windows for some reason
          Move-Item -Path target/release/ed25519_bip32.dll -Destination artifacts/libed25519_bip32.dll
          #Compress-Archive -Path artifacts/* -Destination {{ matrix.artifact }}
      - name: Create release artifact
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'tar'
          path: artifacts
          # exclude dirname from archive
          custom: -C artifacts
          filename: libed25519_bip32_${{ matrix.name }}.tar.gz
          # prevents error: tar: .: file changed as we read it
          #exclusions: .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: libed25519_bip32_${{ matrix.name }}.tar.gz
          # temporary
          tag_name: v1.0.1
