name: Build and Release Dylib

on: push
#  release:
#    types: [created]

jobs:
  release:
    strategy:
      matrix:
        include:
          - image: macos-latest
            name: macos-amd64
            extension: dylib
          - image: ubuntu-latest
            name: linux-amd64
            extension: so
          - image: windows-latest
            name: windows-amd64
            extension: dll
          - image: [self-hosted, macos, arm64]
            name: macos-arm64
            extension: dylib
          - image: [self-hosted, linux, arm64]
            name: linux-arm64
            extension: so
    runs-on: ${{ matrix.image }}
    name: Release ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: make deps
      - name: Regenerate C Header and Check
        run: make diff
      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE 
            ed25519_bip32.h
            target/release/libed25519_bip32.${{ matrix.extension }}
